---
language: python
python: "2.7"
cache: pip
dist: trusty
services:
  - docker

# Use the new container infrastructure
sudo: false

# Set environment
env:
  matrix:
    - IMAGE_NAME="ubuntu:16.04-builded"
    - IMAGE_NAME="debian:8-builded"
    - IMAGE_NAME="debian:9-builded"
    - IMAGE_NAME="centos:7-builded"
    - IMAGE_NAME="centos:6-builded"

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
